#!/bin/bash


# This file is part of the Ristra XMOF2D project.
# Please see the license file at the root of this repository, or at:
#     https://github.com/laristra/XMOF2D/blob/master/LICENSE

# Created by Evgeny Kikinzon.
# Copyright © 2018, Los Alamos National Security, LLC. 
# All rights reserved.

#
# Driver file for building XMOF2D
# 
# -D CMAKE_BUILD_TYPE:STRING=Debug          - for debug library
#                            Release        - for optimized library
#                            RelWithDebInfo - optimized with debug symbols
#                            MinSizeRel     - for min size optimized library
#
# Top-level directory in which to install library and include files e.g.
#
# -D INSTALL_DIR:FILEPATH=/usr/local/packages

# Define platform 
ARCH=`uname -m`
OS=`uname -s`
ARCHOS=${ARCH}_${OS}

# Top level directory where the code lives
XMOF2D_DIR=${PWD}
BUILD_TYPE=Release

BUILD_DIR=${XMOF2D_DIR}/build-${BUILD_TYPE}
INSTALL_DIR=${XMOF2D_DIR}/install-${BUILD_TYPE}

CC=`which gcc`
CXX=`which g++`
FC=`which gfortran`

rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}

cmake \
  -D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
  -D CMAKE_C_COMPILER:FILEPATH=${CC} \
  -D CMAKE_CXX_COMPILER:FILEPATH=${CXX} \
  -D CMAKE_CXX_FLAGS:STRING="-std=c++11" \
  -D INSTALL_DIR:FILEPATH=${INSTALL_DIR} \
  -D ENABLE_FORTRAN:BOOL=ON \
  -D CMAKE_Fortran_COMPILER:FILEPATH=${FC} \
  ${XMOF2D_DIR}
make install
